export const ApiEndpoints = {
  LOGIN: "auth/dashboard/login",
  LOGOUT: "auth/dashboard/logout",
  REFRESH: "auth/dashboard/refresh",
  CREATE_BRANCH: "branches",
  GET_ALL_BRANCHES: "branches",
  DELETE_BRANCH: "branches",
  UPDATE_BRANCH: "branches",
  GET_BRANCH: "branches",
  DOWNLOAD_BRANCHES: "branches/download",
  CREATE_CATEGORY: "category",
  GET_CATEGORIES: "category",
  GET_CATEGORY: "category",
  DELETE_CATEGORY: "category",
  CREATE_MENU: "menu",
  GET_MENUS: "menu",
  GET_MENU: "menu",
  UPDATE_MENU: "menu",
  DELETE_MENU: "menu",
  UPDATE_CATEGORY: "category",
  CREATE_PRODUCT: "products",
  GET_PRODUCTS: "products",
  UPDATE_PRODUCT: "products",
  DELETE_PRODUCT: "products",
  DOWNLOAD_PRODUCTS: "products/download-csv",
  GET_MENU_ITEMS: "menu-items",
  GET_MENU_ITEM: "menu-items",
  CREATE_MENU_ITEM: "menu-items",
  UPDATE_MENU_ITEM: "menu-items",
  DELETE_MENU_ITEM: "menu-items",
  GET_STAFF: "staff",
  CREATE_STAFF: "staff",
  UPDATE_STAFF: "staff",
  DELETE_STAFF: "staff",
  DOWNLOAD_STAFF: "staff/download",
  GET_ORDERS: "orders",
  FILTERS: "filters",
  SORT_OPTIONS: "sort-options",
  UPLOAD_IMAGE: "upload/image",
} as const;

export type ApiEndpoints = typeof ApiEndpoints[keyof typeof ApiEndpoints];
